## 1. Load MINST dataset

### Import dependencies

In [70]:
import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import OneHotEncoder

### Load Dataset

In [71]:
mnist = fetch_openml('mnist_784')
X, y = mnist.data, mnist.target.astype(int)

c:\python\lib\site-packages\sklearn\datasets\_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [72]:
X = X / 255.0
n_samples = X.shape[0]
n_features = X.shape[1]
n_classes = len(np.unique(y))

In [74]:
enc = OneHotEncoder()
Y = enc.fit_transform(y.values.reshape(-1, 1)).toarray()

In [75]:
dataset = shuffle(df)

#### K-Fold cross validation implementaion

In [11]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [12]:
def accuracy(y, y_hat):
    true=0
    for i in range(len(y)) :
        if y[i] == y_hat[i]:
            true+=1
    return (true / len(y)) * 100

## 5. Implement Logistic Regression with different values for learning rate

### Import dependencies

In [13]:
import numpy as np

In [103]:
def one_hot_encode(y, no_classes):
    y_new = np.zeros((len(y), no_classes))
    for i in range(no_classes):
        for j in range(len(y)):
            if(y[i] == i):
                y_new[j][i] = 1
                continue
    return y_new

In [104]:
def softmax(z, w, b):
    z = np.dot(X, w) + b
    exp_z = np.exp(z)
    return exp_z / np.sum(exp_z, axis=1, keepdims=True)

### Implement Logistic Regression

In [68]:
def softmax(z):
    exp_z = np.exp(z)
    return exp_z / np.sum(exp_z, axis=1, keepdims=True)

In [107]:
class Logistic:
    def __init__(self, eta=0.0008, epochs=100, no_classes=10):
        self.w = None
        self.b = None
        self.eta = None
        self.epochs = None
        self.no_classes = None
    def unit_step(self, z):
        for i in range(len(z)):
            if z[i] >0.5:
                z[i] = 1
            else:
                z[i]=0
        return z
    
    def cost(self,y_hat,y):
        m = len(y)
        return -np.mean(-y * np.log(y_hat) - ((1-y) * np.log(1-y_hat)))
    
    def get_net_input(self, X, y):
        return (np.dot(X, self.w)) + self.b
    
    def update_weight(self, y_pred, y, X):
        return self.w - ((self.eta * np.dot((y_pred - y),X)) / len(X))
    
    def update_bias(self, y_pred, y):
        return self.b - (self.eta * np.mean((y_pred - y)))
    
    def activation(self, z):
        return 1 / (1 + np.exp(-z))
    
    def fit(self, X, y, eta, epochs, no_classes):
        m = len(X)
        self.w = np.zeros((10, X.shape[0]))
        self.b = np.random.uniform(low=-0.01, high=0.01, size=1)

        self.eta = eta
        self.epochs = epochs
        self.no_classes = no_classes
        z = np.zeros(no_classes)
        for epoch in range(epochs):
            for classifer in range(no_classes):
            
                #Get net input
                z = self.get_net_input(X, y)
                
                #apply activation function
                z = self.activation(z)
                
                #Calc error
                y_pred = softmax(z.copy(), self.w[classifer], self.b)
                error = self.cost(y_pred, y)
                
                #Update Weight and bias
                self.w[classifer] = self.update_weight(y_pred, y, X)
                self.b = self.update_bias(y_pred, y)

                if error == 0:
                    break
                
    def predict(self, X):
        return self.unit_step((np.dot(self.w, X.T)) + self.b)
    
    def get_weights(self):
        return [self.w, self.b]
    

## 6. Report difference accuracy for the different learning rate

In [108]:
X = dataset.drop(columns = ['Target'])
y = dataset['Target']

In [109]:
X = X.to_numpy()
y = y.to_numpy()
test = one_hot_encode(y,10)
print(test)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [110]:
clf = Logistic(0.008, 100, 10)

In [111]:
clf.fit(X, y, 0.008, 100, 10)

ValueError: shapes (1797,64) and (10,1797) not aligned: 64 (dim 1) != 10 (dim 0)